<?php get_header(); ?>
<main>
	<section class="hero page-hero products-hero"><div class="hero-copy fade-in"><p class="eyebrow">Colección completa</p><h1>Ocho sabores. Tu forma de servirlos.</h1><p class="hero-text">Desde los cítricos más frescos hasta los perfiles frutales y especiados. Elegí uno o armá tu propia colección.</p></div><img class="page-hero-products fade-in" src="<?php echo esc_url( brumma_image_url( 'coleccion.webp' ) ); ?>" alt="Colección de espumas saborizadas"><span class="page-number">08</span></section>
	<div class="filters fade-in" aria-label="Filtrar sabores"><button class="filter-btn active" type="button" data-filter="all">Todos</button><button class="filter-btn" type="button" data-filter="frescos">Frescos</button><button class="filter-btn" type="button" data-filter="intensos">Intensos</button><button class="filter-btn" type="button" data-filter="tropicales">Tropicales</button><button class="filter-btn" type="button" data-filter="especiados">Especiados</button></div>
	<section class="section catalog-section"><div class="product-grid catalog-grid real-products">
	<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); get_template_part( 'template-parts/product-card', null, array( 'product' => wc_get_product( get_the_ID() ) ) ); endwhile; else : ?><p>No hay sabores disponibles en este momento.</p><?php endif; ?>
	</div><?php the_posts_pagination(); ?></section>
	<section class="bundle-section bundle-with-photo fade-in"><div><p class="eyebrow">Colección para descubrir</p><h2>Una barra llena de color.</h2><p>Combiná tus sabores favoritos y encontrá nuevas formas de terminar cada bebida. Ideales para uso en casa, gastronomía y eventos.</p><a class="btn" href="<?php echo esc_url( home_url( '/contacto/' ) ); ?>">Consultar por combos</a></div><img src="<?php echo esc_url( brumma_image_url( 'coleccion.webp' ) ); ?>" alt="Colección de espumas saborizadas"></section>
	<section class="section faq-section"><div class="section-heading fade-in"><p class="eyebrow">Antes del primer sorbo</p><h2>Preguntas frecuentes.</h2></div><div class="faq-list fade-in"><div class="faq-item"><button class="faq-question" type="button">¿Cómo se usa Brumma?<i class="fa-solid fa-plus"></i></button><div class="faq-answer"><p>Agitá suavemente, serví el trago y aplicá una capa fina al final.</p></div></div><div class="faq-item"><button class="faq-question" type="button">¿Con qué tragos combina?<i class="fa-solid fa-plus"></i></button><div class="faq-answer"><p>Funciona especialmente bien en cócteles cítricos, aperitivos, sours y tragos con espumante.</p></div></div><div class="faq-item"><button class="faq-question" type="button">¿Cuántas copas rinde?<i class="fa-solid fa-plus"></i></button><div class="faq-answer"><p>Como referencia, un envase acompaña entre 18 y 24 cócteles.</p></div></div></div></section>
</main>
<?php get_footer(); ?>
