<?php get_header(); ?>
<main>
	<section class="hero home-hero hero-center">
		<div class="hero-visual hero-photo fade-in reveal-scale"><img src="<?php echo esc_url( brumma_image_url( 'hero-manzana-verde.webp' ) ); ?>" alt="Espuma sabor manzana verde junto a un cóctel con espuma"></div>
		<div class="hero-copy fade-in hero-copy-centered"><p class="eyebrow">Espumas saborizadas · Para tragos y mucho más</p><h1>Una espuma. Cientos de formas de disfrutarla.</h1><p class="hero-text">Sabores intensos, textura cremosa y una aplicación simple para transformar tragos, cafés, postres y bebidas sin alcohol.</p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url( brumma_shop_url() ); ?>">Descubrir sabores <i class="fa-solid fa-arrow-right"></i></a><a class="text-link" href="#ritual">Conocer el ritual</a></div><div class="hero-note"><span>08 sabores</span><p>Agitá. Coroná. Disfrutá.</p></div></div>
	</section>
	<section class="marquee" aria-label="Atributos de Brumma"><div class="marquee-track"><span>SABOR</span><i>✦</i><span>TEXTURA</span><i>✦</i><span>COLOR</span><i>✦</i><span>CREATIVIDAD</span><i>✦</i><span>ESPUMA</span><i>✦</i><span>AROMA</span><i>✦</i><span>SABOR</span><i>✦</i><span>TEXTURA</span><i>✦</i><span>COLOR</span><i>✦</i><span>CREATIVIDAD</span><i>✦</i><span>ESPUMA</span><i>✦</i><span>AROMA</span></div></section>
	<section class="section ritual" id="ritual"><div class="ritual-layout"><div class="ritual-visual fade-in reveal-left"><img src="<?php echo esc_url( brumma_image_url( 'ritual-frutos-rojos.webp' ) ); ?>" alt="Espuma de frutos rojos junto a una bebida preparada"><div class="ritual-visual-tag"><span>01</span><p>Aplicación simple.<br>Resultado inmediato.</p></div></div><div class="ritual-content fade-in reveal-right"><div class="section-heading"><p class="eyebrow">Una experiencia en tres actos</p><h2>La última capa.<br>La primera impresión.</h2><p>Una espuma llena de sabor transforma la presentación y la textura en sólo unos segundos.</p></div><div class="steps-list"><article class="step-line"><span class="step-number">01</span><i class="fa-solid fa-arrows-rotate"></i><div><h3>Agitá</h3><p>Mové bien el envase antes de cada uso para activar la textura.</p></div></article><article class="step-line"><span class="step-number">02</span><i class="fa-solid fa-wand-magic-sparkles"></i><div><h3>Aplicá</h3><p>Serví directamente sobre la bebida o el postre terminado.</p></div></article><article class="step-line"><span class="step-number">03</span><i class="fa-regular fa-face-smile"></i><div><h3>Disfrutá</h3><p>Sumá color, aroma y una textura cremosa desde el primer vistazo.</p></div></article></div></div></div></section>
	<section class="section flavors-section"><div class="section-top fade-in"><div><p class="eyebrow">Colección esencial</p><h2>Un sabor para cada noche.</h2></div><a class="text-link" href="<?php echo esc_url( brumma_shop_url() ); ?>">Ver toda la colección <i class="fa-solid fa-arrow-right"></i></a></div><div class="product-grid featured-grid real-products">
	<?php
	$featured_products = function_exists( 'wc_get_products' ) ? wc_get_products( array( 'limit' => 3, 'status' => 'publish', 'orderby' => 'menu_order', 'order' => 'ASC' ) ) : array();
	foreach ( $featured_products as $product ) {
		get_template_part( 'template-parts/product-card', null, array( 'product' => $product ) );
	}
	?>
	</div></section>
	<section class="editorial-section fade-in"><div class="editorial-art real-editorial"><img src="<?php echo esc_url( brumma_image_url( 'editorial-frutilla.webp' ) ); ?>" alt="Espuma sabor frutilla en una escena tropical"></div><div class="editorial-copy"><p class="eyebrow">Más que coctelería</p><h2>Una textura que abre nuevas ideas.</h2><p>Usala sobre tragos con o sin alcohol, cafés fríos, milkshakes, helados y postres. La espuma aporta sabor, volumen y un acabado que se disfruta desde el primer vistazo.</p><a class="btn btn-outline" href="<?php echo esc_url( home_url( '/nosotros/' ) ); ?>">Conocer el producto</a></div></section>
	<section class="section quote-section fade-in"><i class="fa-solid fa-quote-left"></i><blockquote>“El primer sorbo empieza mucho antes de tocar la copa.”</blockquote><p>Manifiesto Brumma</p></section>
	<section class="newsletter fade-in"><p class="eyebrow">Entrá al círculo</p><h2>Nuevos sabores.<br>Noches por descubrir.</h2><p>Seguinos para conocer lanzamientos, recetas y rituales de barra.</p><a class="btn btn-primary" href="https://www.instagram.com/brumma.arg/" target="_blank" rel="noopener"><i class="fa-brands fa-instagram"></i> Seguir en Instagram</a></section>
</main>
<?php get_footer(); ?>
